spring:
  application:
    name: sensor-statistics
  datasource:
    url: jdbc:postgresql://localhost:5433/sensor_statistics
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  port: 8081
  
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html   