name: monitor-sensors

networks:
  monitor-network:
    name: monitor-network
    driver: bridge  

services:
  # Service db
  postgres:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: monitor_sensors
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - monitor-network

  # Service app
  app:
    image: monitor-sensors-app:latest
    container_name: monitor-sensors-app
    build:
      context: .
      dockerfile: Dockerfile    
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/monitor_sensors
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      SPRING_LIQUIBASE_ENABLED: true  
      SPRING_LIQUIBASE_CHANGE-LOG: classpath:db/changelog/db.changelog-master.yaml            
    depends_on:
      - postgres
    networks:
      - monitor-network      

volumes:
  postgres_data: {}
